services:
  travel-flow-db:
    image: mysql:8
    container_name: safarihub-db
    ports:
      - "3307:3306"
    networks:
      - safarihub-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: TravelFlow
    volumes:
      - safarihub-vol:/var/lib/mysql

  travel-flow-app:
    build:
      context: ./SafariHub
    image: safarihub-app-img
    container_name: safarihub-app
    ports:
      - "8081:8081"
    depends_on:
      - travel-flow-db
    networks:
      - safarihub-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://travel-flow-db:3306/TravelFlow?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

networks:
  safarihub-net:
    driver: bridge

volumes:
  safarihub-vol:
